services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: gestao-multisacadas
      POSTGRES_USER: multisacadas
      POSTGRES_PASSWORD: MultiS@c@d@s
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: