spring:
  application:
    name: gestao-multisacadas
  datasource:
    url: jdbc:postgresql://localhost:5433/gestao-multisacadas
    username: multisacadas
    password: MultiS@c@d@s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yml
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  security:
    user:
      name: admin
      password: '@dm!N'

server:
  port: 8082

